- name: my web server setup
  hosts: web
  vars:
   mypack: php
   

  tasks:
    - name: install apache server
      package:
       name: "{{  item }}"
       state: present
      with_items:
       - httpd
       - php

    - name: creating web document folder
      file:
       path: /webcontent
       state: directory
       owner: apache
       mode: 0750

    - name: conf web file
      copy:
       dest: /etc/httpd/conf.d/my.conf
       src: /files/my.conf
       owner: apache
       mode: 0640

    - name: deploy php site
      copy:
       dest: /webcontent
       src: /files/index.php
       owner: apache
       mode: 0640
       notify: web_restart

    - name: start web service
      service:
       name: httpd
       state: started
       enabled: yes

    - name: enable 80 port in firewalld
      firewalld:
       service: http
       state: enabled
       permanent: true
       immediate: true
  
  handlers:
    - name: web_restart
      service:
       name: httpd
       state: restarted
       enabled: yes

